### ISSUE TITLE
Anaconda project 0.8.4 reports its version as 0.8.3

### ISSUE THREAD

**Issue by jlstevens** [Anaconda-Platform/anaconda-project#254] opened 2020-02-25 22:22 UTC
Likely to be an extremely easy fix but I think it is worth filing an issue in case anyone else gets confused by this.

To reproduce:

```bash
$ conda create -n example python
$ conda activate example
$ conda install anaconda-project=0.8.4 # 0.8.4 then lists as downloaded
$ anaconda-project --version
0.8.3
```

**Comment by AlbertDeFusco** [comment] 2020-03-06 23:07
I believe this is fixed on master. Here's the output from my dev environment where I did `pip install -e`

```
>anaconda-project --version
v0.8.4+55.g19821ac
```

**Comment by sanbales** [comment] 2020-04-03 20:40
Is this a duplicate of https://github.com/Anaconda-Platform/anaconda-project/issues/238?

**Comment by mcg1969** [comment] 2020-06-07 17:46
It is indeed.

**Closed by mcg1969** 2020-06-07 17:46 UTC
